server:
  port: 8083
  
spring:
  data:
    mongodb:
      uri:  mongodb+srv://Satyam:Satyam123@cluster0.zfgcs.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      
  application:
    name: CUSTOMER-SERVICE
